import {
  DotMatrixIcon,
  DotmCircular1,
  DotmCircular10,
  DotmCircular11,
  DotmCircular12,
  DotmCircular13,
  DotmCircular14,
  DotmCircular15,
  DotmCircular16,
  DotmCircular17,
  DotmCircular18,
  DotmCircular19,
  DotmCircular2,
  DotmCircular20,
  DotmCircular3,
  DotmCircular4,
  DotmCircular5,
  DotmCircular6,
  DotmCircular7,
  DotmCircular8,
  DotmCircular9,
  DotmHex1,
  DotmHex10,
  DotmHex2,
  DotmHex3,
  DotmHex4,
  DotmHex5,
  DotmHex6,
  DotmHex7,
  DotmHex8,
  DotmHex9,
  DotmSquare1,
  DotmSquare10,
  DotmSquare11,
  DotmSquare12,
  DotmSquare13,
  DotmSquare14,
  DotmSquare15,
  DotmSquare16,
  DotmSquare17,
  DotmSquare18,
  DotmSquare19,
  DotmSquare2,
  DotmSquare20,
  DotmSquare3,
  DotmSquare4,
  DotmSquare5,
  DotmSquare6,
  DotmSquare7,
  DotmSquare8,
  DotmSquare9,
  DotmTriangle1,
  DotmTriangle10,
  DotmTriangle11,
  DotmTriangle12,
  DotmTriangle13,
  DotmTriangle14,
  DotmTriangle15,
  DotmTriangle16,
  DotmTriangle17,
  DotmTriangle18,
  DotmTriangle19,
  DotmTriangle2,
  DotmTriangle20,
  DotmTriangle3,
  DotmTriangle4,
  DotmTriangle5,
  DotmTriangle6,
  DotmTriangle7,
  DotmTriangle8,
  DotmTriangle9,
  type DotMatrixCommonProps
} from "@/loaders";
import type { ComponentType } from "react";

export type LoaderPreviewComponent = ComponentType<DotMatrixCommonProps>;

export const loaderComponentMap: Record<string, LoaderPreviewComponent> = {
  "dotm-square-1": DotmSquare1,
  "dotm-square-2": DotmSquare2,
  "dotm-square-3": DotmSquare3,
  "dotm-square-4": DotmSquare4,
  "dotm-square-5": DotmSquare5,
  "dotm-square-6": DotmSquare6,
  "dotm-square-7": DotmSquare7,
  "dotm-square-8": DotmSquare8,
  "dotm-square-9": DotmSquare9,
  "dotm-square-10": DotmSquare10,
  "dotm-square-11": DotmSquare11,
  "dotm-square-12": DotmSquare12,
  "dotm-square-13": DotmSquare13,
  "dotm-square-14": DotmSquare14,
  "dotm-square-15": DotmSquare15,
  "dotm-square-16": DotmSquare16,
  "dotm-square-17": DotmSquare17,
  "dotm-square-18": DotmSquare18,
  "dotm-square-19": DotmSquare19,
  "dotm-square-20": DotmSquare20,
  "dotm-circular-1": DotmCircular1,
  "dotm-circular-2": DotmCircular2,
  "dotm-circular-3": DotmCircular3,
  "dotm-circular-4": DotmCircular4,
  "dotm-circular-5": DotmCircular5,
  "dotm-circular-6": DotmCircular6,
  "dotm-circular-7": DotmCircular7,
  "dotm-circular-8": DotmCircular8,
  "dotm-circular-9": DotmCircular9,
  "dotm-circular-10": DotmCircular10,
  "dotm-circular-11": DotmCircular11,
  "dotm-circular-12": DotmCircular12,
  "dotm-circular-13": DotmCircular13,
  "dotm-circular-14": DotmCircular14,
  "dotm-circular-15": DotmCircular15,
  "dotm-circular-16": DotmCircular16,
  "dotm-circular-17": DotmCircular17,
  "dotm-circular-18": DotmCircular18,
  "dotm-circular-19": DotmCircular19,
  "dotm-circular-20": DotmCircular20,
  "dotm-triangle-1": DotmTriangle1,
  "dotm-triangle-2": DotmTriangle2,
  "dotm-triangle-3": DotmTriangle3,
  "dotm-triangle-4": DotmTriangle4,
  "dotm-triangle-5": DotmTriangle5,
  "dotm-triangle-6": DotmTriangle6,
  "dotm-triangle-7": DotmTriangle7,
  "dotm-triangle-8": DotmTriangle8,
  "dotm-triangle-9": DotmTriangle9,
  "dotm-triangle-10": DotmTriangle10,
  "dotm-triangle-11": DotmTriangle11,
  "dotm-triangle-12": DotmTriangle12,
  "dotm-triangle-13": DotmTriangle13,
  "dotm-triangle-14": DotmTriangle14,
  "dotm-triangle-15": DotmTriangle15,
  "dotm-triangle-16": DotmTriangle16,
  "dotm-triangle-17": DotmTriangle17,
  "dotm-triangle-18": DotmTriangle18,
  "dotm-triangle-19": DotmTriangle19,
  "dotm-triangle-20": DotmTriangle20,
  "dotm-hex-1": DotmHex1,
  "dotm-hex-2": DotmHex2,
  "dotm-hex-3": DotmHex3,
  "dotm-hex-4": DotmHex4,
  "dotm-hex-5": DotmHex5,
  "dotm-hex-6": DotmHex6,
  "dotm-hex-7": DotmHex7,
  "dotm-hex-8": DotmHex8,
  "dotm-hex-9": DotmHex9,
  "dotm-hex-10": DotmHex10
};

export function getLoaderPreviewComponent(slug: string): LoaderPreviewComponent {
  return loaderComponentMap[slug] ?? DotMatrixIcon;
}
